version: "3.3"

services:
  sqlserver:
    container_name: GameBalance
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "admin123@"
      MSSQL_PID: "Developer"
      MSSQL_DATA_DIR: "/var/opt/mssql"
    ports:
      - "1533:1433"
    volumes:
      - mssql:/var/opt/mssql

volumes:
  mssql: